#!/usr/bin/env bash
# first update the system and install ufw
sudo apt update && sudo apt install ufw -y

# Provide permission
sudo ufw default deny incoming
sudo ufw default allow outgoing

# give permission to port (22,80,443)
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp

sudo ufw enable