#!/usr/bin/env bash
# config the load balancer on the server

apt-get update -y
apt-get install -y haproxy

[ -f /etc/default/haproxy ] && sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.orig

cat > /etc/haproxy/haproxy.cfg <<EOF
global
    log /dev/log local0
    log /dev/log local1 notice
    daemon
    maxconn 256

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    timeout connect 5000ms
    timeout client  50000ms
    timeout server  50000ms

frontend web_frontend
    bind *:80
    default_backend web_backend

backend web_backend
    balance roundrobin
    server web-01 34.205.72.228:80 check
    server web-02 54.165.198.141:80 check
EOF


haproxy -c -f /etc/haproxy/haproxy.cfg || exit 1

service haproxy restart
