#!/usr/bin/env bash
# Install nginx and configure to custom error page 404

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

sudo sed -i '/listen \[::\]:80 default_server;/a \\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx restart
